<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Shaileshs-MacBook-Air.local" name="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy" tests="6" failures="0" timestamp="01 Jan 2020 02:30:29 GMT" time="5.032" errors="1">
  <testcase name="checkContentLength" time="0.000" classname="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy">
    <skipped/>
  </testcase> <!-- checkContentLength -->
  <testcase name="checkResponseTime" time="0.000" classname="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkstatusLine" time="0.000" classname="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy">
    <skipped/>
  </testcase> <!-- checkstatusLine -->
  <testcase name="getEmployeeData" time="5.032" classname="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy">
    <error type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy.getEmployeeData(TC_025_CheckExtraCharacterWithGetfunctionaltiy.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 30 more
]]>
    </error>
  </testcase> <!-- getEmployeeData -->
  <testcase name="checkResposeBody" time="0.000" classname="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy">
    <skipped/>
  </testcase> <!-- checkResposeBody -->
  <testcase name="checkStatusCode" time="0.000" classname="com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
</testsuite> <!-- com.heroes.testCases.TC_025_CheckExtraCharacterWithGetfunctionaltiy -->
